"""initial

Revision ID: 3a7eda0f3d10
Revises: dcd6b9a68427
Create Date: 2024-01-04 06:53:12.387569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7eda0f3d10'
down_revision: Union[str, None] = 'dcd6b9a68427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_threads', 'thread_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_threads', 'thread_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
