"""initial

Revision ID: a3c34ca79a4a
Revises: 38fc2a56bc09
Create Date: 2024-01-08 22:43:20.075194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c34ca79a4a'
down_revision: Union[str, None] = '38fc2a56bc09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('daily_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'daily_limit')
    # ### end Alembic commands ###
