"""initial

Revision ID: dcd6b9a68427
Revises: 
Create Date: 2024-01-04 06:52:04.565536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd6b9a68427'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('mailing_targets',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('was_answered_by_target', sa.Boolean(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('message_threads',
    sa.Column('thread_username', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('sender_username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_messages',
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker', sa.String(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('sender_username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers')
    op.drop_table('new_messages')
    op.drop_table('message_threads')
    op.drop_table('mailing_targets')
    op.drop_table('admins')
    # ### end Alembic commands ###
